/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed": "#e6e2d8",
        "surface-container-high": "#e9e7eb",
        "secondary-container": "#e6e2d8",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-variant": "#e4e2e5",
        "on-background": "#1b1b1e",
        "on-secondary-fixed": "#1c1c16",
        "on-secondary-container": "#66645d",
        "on-primary-fixed-variant": "#364768",
        "primary": "#031635",
        "on-primary-fixed": "#081b3a",
        "secondary-fixed-dim": "#cac6bd",
        "on-primary-container": "#8293b8",
        "primary-container": "#1a2b4b",
        "surface-container": "#efedf0",
        "on-secondary-fixed-variant": "#484740",
        "outline-variant": "#c5c6cf",
        "on-tertiary-fixed": "#291800",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b6c6ef",
        "on-surface-variant": "#44474e",
        "inverse-primary": "#b6c6ef",
        "tertiary-fixed": "#ffddb1",
        "tertiary-container": "#3e2700",
        "surface-dim": "#dbd9dc",
        "tertiary-fixed-dim": "#e8c08a",
        "surface-tint": "#4e5e81",
        "surface": "#fbf8fc",
        "surface-container-low": "#f5f3f6",
        "on-error-container": "#93000a",
        "inverse-surface": "#303033",
        "on-surface": "#1b1b1e",
        "inverse-on-surface": "#f2f0f3",
        "surface-container-highest": "#e4e2e5",
        "on-primary": "#ffffff",
        "surface-bright": "#fbf8fc",
        "on-tertiary-container": "#b08d5b",
        "secondary": "#605e57",
        "background": "#fbf8fc",
        "outline": "#75777f",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "tertiary": "#231400",
        "on-tertiary-fixed-variant": "#5d4217",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d8e2ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sm": "8px",
        "lg": "24px",
        "container-padding": "24px",
        "xl": "32px",
        "gutter": "20px",
        "md": "16px",
        "xs": "4px",
        "unit": "4px"
      },
      "fontFamily": {
        "stat-lg": ["Manrope"],
        "headline-md": ["Manrope"],
        "label-bold": ["Inter"],
        "headline-xl": ["Manrope"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"]
      },
      "fontSize": {
        "stat-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-bold": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-xl": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
